### ISSUE TITLE
请问sm4只支持16位字符加密吗？

### ISSUE THREAD

**Issue by 1003824904** [toruneko/lua-resty-crypto#1]
请问sm4只支持16位字符加密吗？

**Comment by toruneko** [comment]
是你说加密的密码吗？密码是16位字符。

**Comment by 1003824904** [comment]
加密的数据超过16位也会报错的

**Comment by toruneko** [comment]
```
local resty_crypto = require "resty.crypto"
local resty_sm4 = require "resty.sm4"
local sm4, err = resty_crypto.new("secret", nil, resty_sm4.cipher())
if not sm4 then
    error(err)
end
local enc_data, err = sm4:encrypt("abc")
if err then
    error(err)
end
ngx.say(sm4:decrypt(enc_data))
```
用这个方式，会对密码和数据做padding

**Comment by 1003824904** [comment]
这种方式的密钥和数据都可以不是hex格式的是吧？

**Comment by toruneko** [comment]
密码不用，加密结果`enc_data`是二进制的，需要用hex或者base64编码，才是可读的。

**Comment by 1003824904** [comment]
好的，谢谢，我试试

**Comment by 1003824904** [comment]
请问用这种方式加密是用的ECB模式吗？如果想有CBC模式请问该怎么调用？因为和nodejs互通过程中，使用同样的密钥和原文，加密出来的数据不同，猜想是对密钥做过特殊处理了吧？

**Comment by toruneko** [comment]
默认是cbc，`resty_sm4.cipher()` 这个方法有两个参数
`resty_sm4.cipher("cbc", "128")`    
第二个目前是写死了128bit

**Comment by 1003824904** [comment]
好的，谢谢解答

**Comment by 1003824904** [comment]
不好意思，昨天说错了，我想用ecb模式，但是resty_sm4.cipher("ecb")这样传参好像不起作用，加密结果跟不传参数一样

**Comment by toruneko** [comment]
确实没有实现， 刚已经提交了。
支持ECB CBC OFB CFB CTR 模式

**Comment by 1003824904** [comment]
厉害，感谢！

**Comment by toruneko** [comment]
你的openresty环境中openssl版本是1.1.1吗？

**Comment by 1003824904** [comment]
是的，，特意升级，为了支持国密

**Comment by toruneko** [comment]
哈哈，那其实可以更简单。
`https://www.openssl.org/docs/man1.1.1/man3/EVP_sm4_ecb.html`
```
local cipher = C.EVP_sm4_ecb()
```

这个项目是因为openssl1.1.0不支持国密，才做的。

**Comment by 1003824904** [comment]
好吧，，感谢指导！！！
