### ISSUE TITLE
使用sm2验签时遇到的疑问

### ISSUE THREAD

**Issue by smallbirdwy** [toruneko/lua-resty-crypto#10]
local sm2, err = resty_sm2.new({
    public_key = pubkey,
    algorithm = "sm3",
    id = "1234567812345678"
})

当我验签失败的时候 work process xxxxx exited on signal 11 (core dumped)

验证签名失败的时候想根据true false这样去判断做自定义返回,这边可以怎么做

**Comment by smallbirdwy** [comment]
local ok,err = sm2:verify(data.signature)

**Comment by smallbirdwy** [comment]
local ok,err = sm2:verify(data, signature)

**Comment by smallbirdwy** [comment]
local ok,err = sm2:verify(data, signature)
当我验签成功的时候 boolean为true
当我验签失败的时候 work process xxxxx exited on signal 11 (core dumped)

**Comment by smallbirdwy** [comment]
nginx version:openresty/1.15.8.1

**Comment by toruneko** [comment]
是因为get_error遇到未知的code。马上修复一下。

**Comment by smallbirdwy** [comment]
感谢
