### ISSUE TITLE
我有一个疑问

### ISSUE THREAD

**Issue by ssmallbirds** [toruneko/lua-resty-crypto#11]
local sm2, _ = resty_sm2.new({
    private_key = prvkey,
    public_key = pubkey,
    algorithm = "sm3",
    id = "toruneko@outlook.com"
})
sm2:sign(data)
我有一个疑问，再签名的时候必须要设置public_key吗，当我new的时候，没设置公钥的时候 sm2(a nil value)
不是私钥签名，公钥验签吗，签名的时候和public_key应该是没关联的吧

**Comment by oupy** [comment]
请问curver not found 报这个错是什么原因呢

**Comment by toruneko** [comment]
你说的很有道理，这个我一开始也很疑惑。

不过持有私钥一方，肯定有公钥。而持有公钥一方，肯定没有私钥。这样似乎不影响使用，所以就没有深究下去了。

**Comment by toruneko** [comment]
> 请问curver not found 报这个错是什么原因呢

查看一下你的openssl版本，建议使用1.1.1最新版本

**Comment by alixiaodi** [comment]
@toruneko 使用了 openssl1.1.1 的版本还是会报错  curver not found
