### ISSUE TITLE
sm4加密后的数据类型是什么

### ISSUE THREAD

**Issue by ssmallbirds** [toruneko/lua-resty-crypto#2]
你好sm4加密中，加密英文的时候是可以和java node语言互通，sm4加解密中文的时候就解密不出来了，想问一下，sm4的加解密，加解密的时候用的什么编码格式，编码格式是否可以指定

**Comment by toruneko** [comment]
有例子吗？我调试一下。

**Comment by studentcaoqc** [comment]
不好意思这边弄错了，sm4加解密没问题了，sm3算法对英文加密的时候摘要跟node是一样的，对中文加密摘要是不一样的
                local resty_sm3 = require "resty.sm3"
                local sm3 = resty_sm3:new()
                sm3:update("小花")
                ngx.say(sm3:final())

**Comment by ssmallbirds** [comment]
不好意思，是我们这边node的问题，刚重新跑了一下，sm4和sm3都没问题

**Comment by toruneko** [comment]
ok 欢迎点个星，提交PR哦~
