### ISSUE TITLE
sm2 签名验签支持用sm3做哈希吗？

### ISSUE THREAD

**Issue by 1003824904** [toruneko/lua-resty-crypto#3]
您好：最近注意到更新添加了sm2的支持，有注意到样例中的sm2签名和验签使用的是sha1，想问下支持sm3吗？

local resty_sm2 = require "resty.sm2"
            local resty_str = require "resty.utils.string"
            local string = require "resty.string"
            local data = "ssssssssss"
            local sm2_for_sign, err = resty_sm2.new({
                private_key = "10C9308C5D192CC41C064F7407A846B58ADABEB709EDA4EF77AC0B44767AB329",
                --algorithm = "sha1",
                algorithm = "sm3",
            })
            local signed, err = sm2_for_sign:sign(data)
            local sm2_for_verify, err = resty_sm2.new({
                public_key = "044EA5AF846E8CDD6740AE49E44119F70D0EE771BD24EA6F6C921E17A7AA15E6AC7A9D79DB60DAEB8A71122C815A056DDC1DEE46213179EE734DA9F3FA81BCC70F",
                --algorithm = "sha1",
                algorithm = "sm3",
            })
            local ok , err = sm2_for_verify:verify(data, signed)
            ngx.header["Content-Type"]="application/json";
			ngx.status = 200
            --ngx.say(signed)
            ngx.say(string.to_hex(signed))
            ngx.say(ok)
            ngx.exit(200)

我直接把algorithm 改为sm3会报错。

**Comment by toruneko** [comment]
目前openssl 1.1.1d EC没有支持sm3
openssl1.1.1d EC算法支持的哈希是：
`sha1`, `sha224`, `sha256`, `sha384`, `sha512`
`sha3-224`, `sha3-256`, `sha3-384`, `sha3-512`

**Comment by 1003824904** [comment]
可是我本地使用的是openssl1.1.1c，应该是支持sm3的

**Comment by toruneko** [comment]
是EC算法 不支持，单独使用sm3是没有问题的。

**Comment by toruneko** [comment]
下个版本 openssl 1.1.1e 估计就支持了。

**Comment by 1003824904** [comment]
最近也有用到另一个sm2库  lua-openssl，他这个库就可以SM3withSM2签名，不知道他是自己实现的算法，还是也是用了openssl

**Comment by toruneko** [comment]
确实是有问题，应该调用了ec的算法，应该要调用sm2的sign和verify才对。

**Comment by toruneko** [comment]
已经修复了。可以支持sm3。

**Comment by 1003824904** [comment]
厉害，我马上试试。感谢！！！

**Comment by toruneko** [comment]
目前只能支持到sign和verify，加解密还没时间弄。

**Comment by 1003824904** [comment]
收到，这边暂时也只用到了sign和verify，刚刚试过了和其他语言互通没问题。总之很感谢您，也会一直关注您。
