### ISSUE TITLE
关于sm2报文签名验签的问题

### ISSUE THREAD

**Issue by ssmallbirds** [toruneko/lua-resty-crypto#6]
当我的报文是'{"name":"zhangsan","age":"five"}'这个时候验签就是失败的

**Comment by ssmallbirds** [comment]
但是我的报文如果是‘{"name":"zahngsan"}这个时候就是可以的’

**Comment by toruneko** [comment]
我试过是可以的。方便贴一下你的测试代码么？

**Comment by ssmallbirds** [comment]
是和别的语言互通的时候产生的错误，这边是验证node语言的签名产生的错误，这边又测试了发现是node的问题，不能加太长的报文，感谢您的回复，再次感谢！
